export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST";
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS";
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL";

export const FORM_SEND_RESPONSE_REQUEST = "FORM_SEND_RESPONSE_REQUEST";
export const FORM_SEND_RESPONSE_SUCCESS = "FORM_SEND_RESPONSE_SUCCESS";
export const FORM_SEND_RESPONSE_FAIL = "FORM_SEND_RESPONSE_FAIL";

export const FORM_FILE_UPLOAD_REQUEST = "FORM_FILE_UPLOAD_REQUEST";
export const FORM_FILE_UPLOAD_SUCCESS = "FORM_FILE_UPLOAD_SUCCESS";
export const FORM_FILE_UPLOAD_FAIL = "FORM_FILE_UPLOAD_FAIL";

export const FORM_CREATE_REQUEST = "FORM_CREATE_REQUEST";
export const FORM_CREATE_SUCCESS = "FORM_CREATE_SUCCESS";
export const FORM_CREATE_FAIL = "FORM_CREATE_FAIL";

export const FORM_UPDATE_QUESTION_REQUEST = "FORM_UPDATE_QUESTION_REQUEST";
export const FORM_UPDATE_QUESTION_SUCCESS = "FORM_UPDATE_QUESTION_SUCCESS";
export const FORM_UPDATE_QUESTION_FAIL = "FORM_UPDATE_QUESTION_FAIL";

export const FORM_CREATE_QUESTION_REQUEST = "FORM_CREATE_QUESTION_REQUEST";
export const FORM_CREATE_QUESTION_SUCCESS = "FORM_CREATE_QUESTION_SUCCESS";
export const FORM_CREATE_QUESTION_FAIL = "FORM_CREATE_QUESTION_FAIL";

export const FORM_DELETE_QUESTION_REQUEST = "FORM_DELETE_QUESTION_REQUEST";
export const FORM_DELETE_QUESTION_SUCCESS = "FORM_DELETE_QUESTION_SUCCESS";
export const FORM_DELETE_QUESTION_FAIL = "FORM_DELETE_QUESTION_FAIL";
