export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST";
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS";
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL";

export const FORM_SEND_RESPONSE_REQUEST = "FORM_SEND_RESPONSE_REQUEST";
export const FORM_SEND_RESPONSE_SUCCESS = "FORM_SEND_RESPONSE_SUCCESS";
export const FORM_SEND_RESPONSE_FAIL = "FORM_SEND_RESPONSE_FAIL";
