export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST";
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS";
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL";

export const FORM_SEND_RESPONSE_REQUEST = "FORM_SEND_RESPONSE_REQUEST";
export const FORM_SEND_RESPONSE_SUCCESS = "FORM_SEND_RESPONSE_SUCCESS";
export const FORM_SEND_RESPONSE_FAIL = "FORM_SEND_RESPONSE_FAIL";

export const FORM_FILE_UPLOAD_REQUEST = "FORM_FILE_UPLOAD_REQUEST";
export const FORM_FILE_UPLOAD_SUCCESS = "FORM_FILE_UPLOAD_SUCCESS";
export const FORM_FILE_UPLOAD_FAIL = "FORM_FILE_UPLOAD_FAIL";

export const FORM_CREATE_REQUEST = "FORM_CREATE_REQUEST";
export const FORM_CREATE_SUCCESS = "FORM_CREATE_SUCCESS";
export const FORM_CREATE_FAIL = "FORM_CREATE_FAIL";
export const FORM_CREATE_RESET = "FORM_CREATE_RESET";

export const FORM_UPDATE_QUESTION_REQUEST = "FORM_UPDATE_QUESTION_REQUEST";
export const FORM_UPDATE_QUESTION_SUCCESS = "FORM_UPDATE_QUESTION_SUCCESS";
export const FORM_UPDATE_QUESTION_FAIL = "FORM_UPDATE_QUESTION_FAIL";
export const FORM_UPDATE_QUESTION_RESET = "FORM_UPDATE_QUESTION_RESET";

export const FORM_UPDATE_REQUEST = "FORM_UPDATE_REQUEST";
export const FORM_UPDATE_SUCCESS = "FORM_UPDATE_SUCCESS";
export const FORM_UPDATE_FAIL = "FORM_UPDATE_FAIL";
export const FORM_UPDATE_RESET = "FORM_UPDATE_RESET";

export const FORM_CREATE_QUESTION_REQUEST = "FORM_CREATE_QUESTION_REQUEST";
export const FORM_CREATE_QUESTION_SUCCESS = "FORM_CREATE_QUESTION_SUCCESS";
export const FORM_CREATE_QUESTION_FAIL = "FORM_CREATE_QUESTION_FAIL";

export const FORM_DELETE_QUESTION_REQUEST = "FORM_DELETE_QUESTION_REQUEST";
export const FORM_DELETE_QUESTION_SUCCESS = "FORM_DELETE_QUESTION_SUCCESS";
export const FORM_DELETE_QUESTION_FAIL = "FORM_DELETE_QUESTION_FAIL";
export const FORM_DELETE_QUESTION_RESET = "FORM_DELETE_QUESTION_RESET";

export const FORM_ANSWERS_REQUEST = "FORM_ANSWERS_REQUEST";
export const FORM_ANSWERS_SUCCESS = "FORM_ANSWERS_SUCCESS";
export const FORM_ANSWERS_FAIL = "FORM_ANSWERS_FAIL";
export const FORM_ANSWERS_RESET = "FORM_ANSWERS_RESET";

export const FORM_ANSWER_REQUEST = "FORM_ANSWER_REQUEST";
export const FORM_ANSWER_SUCCESS = "FORM_ANSWER_SUCCESS";
export const FORM_ANSWER_FAIL = "FORM_ANSWER_FAIL";
export const FORM_ANSWER_RESET = "FORM_ANSWER_RESET";
