export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";

export const GROUP_FORMS_REQUEST = "GROUP_FORMS_REQUEST";
export const GROUP_FORMS_SUCCESS = "GROUP_FORMS_SUCCESS";
export const GROUP_FORMS_FAIL = "GROUP_FORMS_FAIL";
export const GROUP_FORMS_RESET = "GROUP_FORMS_RESET";

export const GROUP_ADMINS_REQUEST = "GROUP_ADMINS_REQUEST";
export const GROUP_ADMINS_SUCCESS = "GROUP_ADMINS_SUCCESS";
export const GROUP_ADMINS_FAIL = "GROUP_ADMINS_FAIL";
export const GROUP_ADMINS_RESET = "GROUP_ADMINS_RESET";

export const GROUP_USERS_REQUEST = "GROUP_USERS_REQUEST";
export const GROUP_USERS_SUCCESS = "GROUP_USERS_SUCCESS";
export const GROUP_USERS_FAIL = "GROUP_USERS_FAIL";
export const GROUP_USERS_RESET = "GROUP_USERS_RESET";

export const GROUP_TITLE_REQUEST = "GROUP_TITLE_REQUEST";
export const GROUP_TITLE_SUCCESS = "GROUP_TITLE_SUCCESS";
export const GROUP_TITLE_FAIL = "GROUP_TITLE_FAIL";
export const GROUP_TITLE_RESET = "GROUP_TITLE_RESET";
