export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_GROUPS_REQUEST = "USER_GROUPS_REQUEST";
export const USER_GROUPS_SUCCESS = "USER_GROUPS_SUCCESS";
export const USER_GROUPS_FAIL = "USER_GROUPS_FAIL";
export const USER_GROUPS_RESET = "USER_GROUPS_RESET";

export const USER_FORMS_REQUEST = "USER_FORMS_REQUEST";
export const USER_FORMS_SUCCESS = "USER_FORMS_SUCCESS";
export const USER_FORMS_FAIL = "USER_FORMS_FAIL";
export const USER_FORMS_RESET = "USER_FORMS_RESET";
